import PageScript from "@/components/PageScript";
import PageShell from "@/components/PageShell";

export default function WatchPage() {
  return (
    <PageShell>
      <section id="watchRoot" className="watch-root -mx-4 grid gap-0 md:mx-0 md:grid-cols-[minmax(0,1fr)_280px] md:items-start md:gap-5 lg:grid-cols-[minmax(0,1fr)_340px] lg:gap-8">
        <div className="player-col">
          <div id="playerWrap" className="player-wrap relative w-full overflow-hidden bg-black md:rounded-2xl md:border" style={{ borderColor: "var(--border-color)", boxShadow: "var(--shadow-heavy)" }}>
            <div id="playerInner" className="player-inner relative mx-auto aspect-video w-full bg-black">
              <video id="video" controls playsInline className="absolute inset-0 h-full w-full"></video>
              <div id="playerOverlay" className="absolute inset-0 z-10 flex flex-col items-center justify-center gap-3 bg-black/60"><div className="h-10 w-10 rounded-full border-[3px] border-white/15 border-t-[#2BA641] animate-spin-slow"></div><p id="playerOverlayText" className="text-sm" style={{ color: "var(--text-secondary)" }}>Memuat video…</p></div>
              <div id="mobileOverlay" className="md:hidden pointer-events-none absolute inset-0 z-40 transition-opacity duration-300">
                <div className="overlay-auto-hide pointer-events-auto absolute inset-x-0 top-0 flex items-start gap-2 px-3 pb-4 pt-[calc(env(safe-area-inset-top)+10px)]" style={{ background: "linear-gradient(180deg, rgba(0,0,0,0.75) 0%, transparent 100%)" }}><a href="/" aria-label="Kembali" className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-black/50 text-white backdrop-blur transition active:scale-90" style={{ borderRadius: "50%" }}><i data-lucide="chevron-left" className="h-5 w-5"></i></a><div className="min-w-0 flex-1"><h1 id="dramaTitleMobile" className="truncate text-sm font-bold leading-tight text-white drop-shadow">—</h1><p className="mt-0.5 flex items-center gap-1.5 text-[11px] text-white/75 drop-shadow"><span id="platformLabelMobile" className="inline-flex items-center gap-1"><i data-lucide="layers" className="h-3 w-3"></i><span>—</span></span><span className="h-1 w-1 rounded-full bg-white/45"></span><span id="epLabelMobile">—</span></p></div><button id="favoriteBtnMobile" aria-label="Favoritkan" className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-black/50 text-white backdrop-blur transition active:scale-90" style={{ borderRadius: "50%" }}><i data-lucide="heart" className="h-4 w-4"></i></button></div>
                <div className="mobile-rail-persist pointer-events-auto absolute right-3 top-1/2 z-30 -translate-y-1/2 flex flex-col items-center gap-3"><button id="prevEpBtnMobile" className="grid h-11 w-11 place-items-center rounded-full border border-white/15 bg-black/55 text-white backdrop-blur transition active:scale-90 disabled:opacity-40" style={{ borderRadius: "50%" }}><i data-lucide="chevron-up" className="h-5 w-5"></i></button><div className="episode-action-stack relative h-14 w-14 overflow-visible"><button id="openEpSheetBtn" className="relative z-10 grid h-14 w-14 place-items-center rounded-full text-black transition active:scale-90" style={{ borderRadius: "50%", background: "var(--accent-control-bg)", color: "var(--accent-control-text)", boxShadow: "var(--shadow-heavy)" }}><i data-lucide="list-video" className="h-6 w-6"></i></button><span id="epBadgeMobile" className="pointer-events-none absolute -top-2 -right-2 z-50 min-w-[28px] rounded-full bg-black px-2 py-1 text-[10px] font-bold leading-none text-white border border-white/20" style={{ borderRadius: "9999px" }}>—</span></div><button id="nextEpBtnMobile" className="grid h-11 w-11 place-items-center rounded-full border border-white/15 bg-black/55 text-white backdrop-blur transition active:scale-90 disabled:opacity-40" style={{ borderRadius: "50%" }}><i data-lucide="chevron-down" className="h-5 w-5"></i></button></div>
                <div id="swipeHint" className="overlay-auto-hide pointer-events-none absolute inset-x-0 bottom-24 flex justify-center"><span className="rounded-full bg-black/60 px-3 py-1.5 text-[11px] font-bold text-white/85 backdrop-blur border border-white/10" style={{ borderRadius: "9999px" }}>↑ Geser untuk ganti episode ↓</span></div>
              </div>
            </div>
          </div>
          <div className="meta-block px-4 pt-5 pb-8 md:px-0 md:pt-6">
            <div className="flex items-start gap-3"><div className="min-w-0 flex-1"><div id="watchTitleSkeleton"><div className="skeleton" style={{ height: "24px", width: "65%", borderRadius: "6px" }}></div><div className="skeleton" style={{ height: "14px", width: "40%", borderRadius: "4px", marginTop: "10px" }}></div></div><h1 id="dramaTitle" style={{ display: "none" }} className="line-clamp-2 text-2xl font-extrabold leading-tight md:text-3xl"></h1><div id="watchMetaRow" style={{ display: "none" }} className="mt-2 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs"><span id="platformLabel" className="inline-flex items-center gap-1"><i data-lucide="layers" className="h-3 w-3"></i><span>—</span></span><span className="h-1 w-1 rounded-full" style={{ background: "var(--border-muted)" }}></span><span id="epLabel">—</span><span className="h-1 w-1 rounded-full" style={{ background: "var(--border-muted)" }}></span><span id="totalLabel">—</span></div></div><button id="shareBtn" aria-label="Bagikan" className="detail-action-icon" style={{ opacity: 0, pointerEvents: "none" }}><i data-lucide="share-2" className="h-4 w-4"></i></button><button id="favoriteBtn" aria-label="Favoritkan" className="detail-action-icon" style={{ opacity: 0, pointerEvents: "none" }}><i data-lucide="heart" className="h-4 w-4"></i></button></div>
            <div id="watchNavSkeleton" className="mt-5 flex gap-3"><div className="flex-1 skeleton" style={{ height: "48px", borderRadius: "9999px" }}></div><div className="flex-1 skeleton" style={{ height: "48px", borderRadius: "9999px" }}></div></div>
            <div id="watchNavReal" className="mt-5 flex gap-3" style={{ display: "none" }}><button id="prevEpBtn" className="inline-flex flex-1 items-center justify-center gap-2 rounded-full px-4 py-3 text-sm font-bold transition disabled:opacity-40 active:scale-95" style={{ borderRadius: "9999px", border: "1px solid var(--border-muted)", background: "var(--bg-raised)", color: "var(--text-primary)", letterSpacing: "1.4px", textTransform: "uppercase" }}><i data-lucide="skip-back" className="h-4 w-4"></i><span>Sebelumnya</span></button><button id="nextEpBtn" className="inline-flex flex-1 items-center justify-center gap-2 rounded-full px-4 py-3 text-sm font-bold transition disabled:opacity-40 active:scale-95" style={{ borderRadius: "9999px", background: "var(--accent-control-bg)", color: "var(--accent-control-text)", border: "1px solid var(--accent-control-border)", letterSpacing: "1.4px", textTransform: "uppercase" }}><span>Berikutnya</span><i data-lucide="skip-forward" className="h-4 w-4"></i></button></div>
            <div id="watchSynopsisSkeleton" className="mt-5"><div className="skeleton" style={{ height: "12px", width: "100%", borderRadius: "4px" }}></div><div className="skeleton" style={{ height: "12px", width: "92%", borderRadius: "4px", marginTop: "8px" }}></div><div className="skeleton" style={{ height: "12px", width: "75%", borderRadius: "4px", marginTop: "8px" }}></div></div>
            <div id="watchSynopsisReal" className="mt-5" style={{ display: "none" }}><p id="dramaSynopsis" className="text-[15px] leading-7 line-clamp-3" style={{ color: "var(--text-secondary)" }}></p><button id="toggleSynopsisBtn" hidden className="mt-1.5 text-xs font-bold transition" style={{ color: "var(--accent)" }}><span>Selengkapnya</span></button></div>
            <div id="watchCast" hidden className="detail-cast-section"></div>
            <div id="watchInfo" hidden className="detail-info-row"></div>
          </div>
        </div>
        <aside className="hidden md:flex md:flex-col sticky top-[80px] mt-0 max-h-[calc(100vh-96px)] overflow-hidden rounded-2xl" style={{ border: "1px solid var(--border-color)", background: "var(--bg-surface)", boxShadow: "var(--shadow-medium)", alignSelf: "start" }}><div className="flex items-center justify-between px-5 pt-4 pb-3" style={{ borderBottom: "1px solid var(--border-color)" }}><h3 className="text-base font-bold" style={{ color: "var(--text-primary)" }}>Episode</h3><span id="epCount" className="text-xs" style={{ color: "var(--text-secondary)" }}>—</span></div><div className="overflow-y-auto p-4"><div id="epList" className="grid gap-2 grid-cols-[repeat(auto-fill,minmax(52px,1fr))]">{Array.from({length:6}).map((_,i)=><div key={i} className="detail-ep-skeleton skeleton"></div>)}</div></div></aside>
      </section>
      <div id="epSheetBackdrop" className="md:hidden hidden fixed inset-0 z-[80] bg-black/60" style={{ backdropFilter: "blur(4px)" }}></div>
      <aside id="epSheet" role="dialog" aria-modal="true" className="md:hidden sheet-translate fixed inset-x-0 bottom-0 z-[81] flex max-h-[78vh] flex-col overflow-hidden rounded-t-2xl pb-[env(safe-area-inset-bottom)]" style={{ borderTop: "1px solid var(--border-color)", background: "var(--sheet-bg)", boxShadow: "var(--shadow-heavy)" }}><div className="sheet-drag-zone mx-auto mt-3 mb-1 h-1 w-10 rounded-full" style={{ background: "var(--border-muted)" }}></div><div className="sheet-drag-zone flex items-center justify-between px-5 py-3" style={{ borderBottom: "1px solid var(--border-color)" }}><div><h3 id="epSheetTitle" className="text-base font-bold" style={{ color: "var(--text-primary)" }}>Episode</h3><p id="epSheetSub" className="text-xs" style={{ color: "var(--text-secondary)" }}>—</p></div><button id="epSheetCloseBtn" aria-label="Tutup" className="grid h-8 w-8 place-items-center transition active:scale-90" style={{ borderRadius: "50%", background: "var(--bg-hover)", color: "var(--text-secondary)" }}><i data-lucide="x" className="h-4 w-4"></i></button></div><div id="epSheetScroller" className="overflow-y-auto px-5 py-4"><div id="epListMobile" className="grid gap-2 grid-cols-[repeat(auto-fill,minmax(50px,1fr))]"></div></div></aside>
      <PageScript id="page-watch" src="/js/watch.js" />
    </PageShell>
  );
}
