export default function BottomNav() {
  return (
    <nav id="bottomNav" aria-label="Navigasi utama" className="fixed inset-x-0 bottom-0 z-50 md:hidden pb-[env(safe-area-inset-bottom)]" style={{ background: "var(--bottomnav-bg)", backdropFilter: "blur(20px)", WebkitBackdropFilter: "blur(20px)", borderTop: "1px solid var(--border-color)" }}>
      <div className="mx-auto grid h-16 max-w-[560px] grid-cols-5">
        <a className="bnav-item relative flex flex-col items-center justify-center gap-1 transition" href="/" data-route="/"><svg className="nav-icon h-5 w-5" style={{ color: "var(--text-secondary)" }} width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg><span className="nav-label text-[10px] font-bold" style={{ color: "var(--text-secondary)", letterSpacing: "0.5px" }} data-i18n="nav.home">Beranda</span></a>
        <a className="bnav-item relative flex flex-col items-center justify-center gap-1 transition" href="/discover" data-route="/discover"><svg className="nav-icon h-5 w-5" style={{ color: "var(--text-secondary)" }} width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"/></svg><span className="nav-label text-[10px] font-bold" style={{ color: "var(--text-secondary)", letterSpacing: "0.5px" }} data-i18n="nav.discover">Jelajahi</span></a>
        <a className="bnav-item relative flex flex-col items-center justify-center gap-1 transition" href="/series" data-route="/series"><svg className="nav-icon h-5 w-5" style={{ color: "var(--text-secondary)" }} width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 11v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8H4Z"/><path d="m4 11-.88-2.87a2 2 0 0 1 1.33-2.5l11.48-3.5a2 2 0 0 1 2.5 1.32l.87 2.87L4 11.01Z"/><path d="m6.6 4.99 3.38 4.2"/><path d="m11.86 3.38 3.38 4.2"/></svg><span className="nav-label text-[10px] font-bold" style={{ color: "var(--text-secondary)", letterSpacing: "0.5px" }} data-i18n="nav.serial">Serial</span></a>
        <a className="bnav-item relative flex flex-col items-center justify-center gap-1 transition" href="/movie" data-route="/movie"><svg className="nav-icon h-5 w-5" style={{ color: "var(--text-secondary)" }} width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><polygon points="10 8 16 12 10 16 10 8"/></svg><span className="nav-label text-[10px] font-bold" style={{ color: "var(--text-secondary)", letterSpacing: "0.5px" }} data-i18n="nav.movie">Movie</span></a>
        <a className="bnav-item relative flex flex-col items-center justify-center gap-1 transition" href="/history" data-route="/history"><svg className="nav-icon h-5 w-5" style={{ color: "var(--text-secondary)" }} width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/><path d="M12 7v5l4 2"/></svg><span className="nav-label text-[10px] font-bold" style={{ color: "var(--text-secondary)", letterSpacing: "0.5px" }} data-i18n="nav.history">Riwayat</span></a>
      </div>
    </nav>
  );
}
